spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
#    username: rookie
#    password: rootROOKIE$
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual